apiVersion: v1
kind: Service
metadata:
  name: nacos
spec:
  ports:
  - name: nacos8848
    nodePort: 30848
    port: 8848
    protocol: TCP
    targetPort: 8848
  - name: nacos9848
    nodePort: 31848
    port: 9848
    protocol: TCP
    targetPort: 9848
  - name: nacos9849
    nodePort: 31849
    port: 9849
    protocol: TCP
    targetPort: 9849
  selector:
    app: nacos
  type: NodePort
