apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruoyi-gen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruoyi-gen
  template:
    metadata:
      labels:
        app: ruoyi-gen
    spec:
      initContainers:
      - name: init-wait-for-nacos
        image: curlimages/curl
        command: ['sh', '-c', "until [ $(curl -sL http://nacos-headless.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local:8848/nacos/actuator/health | grep UP | wc -l) -eq 1 ]; do echo waiting for nacos; sleep 2; done"]
      containers:
      - image: nrt.ocir.io/sehubjapacprod/apmdemo/ruoyi:ruoyigen
        imagePullPolicy: Always
        name: ruoyi-gen
        ports:
        - containerPort: 9202
          protocol: TCP
          name: http-port
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: http-port
          initialDelaySeconds: 5
          failureThreshold: 1
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: http-port
          initialDelaySeconds: 15
          failureThreshold: 1
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /actuator/health
            port: http-port
          failureThreshold: 30
          periodSeconds: 10
      imagePullSecrets:
      - name: dockersecret
